version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: smart-police-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smart_police_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smart-police-backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/smart_police_db?schema=public
      - PORT=5000
      - JWT_SECRET=your_secret_key
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  postgres_data:
